gdown --id 1b-ylF9DmfBvtTfhNJKeNq3Zs5W7yOHu5 --output shapenetcore_partanno_segmentation_benchmark_v0.zip
unzip shapenetcore_partanno_segmentation_benchmark_v0.zip
rm shapenetcore_partanno_segmentation_benchmark_v0.zip
